import { RJSFSchema } from "@rjsf/utils"

export const contactFormSchema: RJSFSchema = {
  type: "object",
  description: "The personal data typically put into a contact form",
  properties: {
    firstName: {
      title: "First Name",
      type: "string",
      description: "the first name of the person",
    },
    lastName: {
      title: "Last Name",
      type: "string",
      description: "the first name of the person",
    },
    address: {
      type: "object",
      title: "Address",
      description: "the home address of the person",
      properties: {
        street: {
          title: "Street",
          type: "string",
          description: "the street of the address including the street number",
        },
        city: {
          title: "City",
          type: "string",
          description:
            "the city of the address. Use your knowledge about cities and their zip codes to get the right one",
        },
        stateAbbreviation: {
          title: "State",
          type: "string",
          description: "the two letter state abbreviation of the address",
          pattern: "^[A-Z]{2}$",
          enum: [
            "AL",
            "AK",
            "AZ",
            "AR",
            "CA",
            "CO",
            "CT",
            "DE",
            "FL",
            "GA",
            "HI",
            "ID",
            "IL",
            "IN",
            "IA",
            "KS",
            "KY",
            "LA",
            "ME",
            "MD",
            "MA",
            "MI",
            "MN",
            "MS",
            "MO",
            "MT",
            "NE",
            "NV",
            "NH",
            "NJ",
            "NM",
            "NY",
            "NC",
            "ND",
            "OH",
            "OK",
            "OR",
            "PA",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VT",
            "VA",
            "WA",
            "WV",
            "WI",
            "WY",
          ],
        },
        zipCode: {
          title: "Zip Code",
          type: "string",
          description: "the zip code of the address",
          pattern: "^\\d{5}$",
        },
      },
      required: ["street", "city", "stateAbbreviation", "zipCode"],
    },
    emailAddress: {
      title: "Email Address",
      type: "string",
      format: "email",
      description: "the email address of the person",
    },
    birthDate: {
      title: "Birth Date",
      type: "string",
      description: "the date of birth of the person in YYYY-MM-DD",
      pattern: "^\\d{4}-\\d{2}-\\d{2}$",
    },
  },
  required: ["firstName", "lastName", "address", "birthDate"],
}
